"""Add unique constraint on tipo_documento and documento

Revision ID: 19fdebacceaa
Revises: c54aa0369694
Create Date: 2024-08-11 22:50:39.791575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19fdebacceaa'
down_revision = 'c54aa0369694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orden_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('forma_pago_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('precio_total', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['forma_pago_id'], ['forma_pago.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('venta_cliente')
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_tipo_documento_documento', ['tipo_documento', 'documento'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.drop_constraint('uix_tipo_documento_documento', type_='unique')

    op.create_table('venta_cliente',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('venta_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('forma_pago_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('precio_total', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='venta_cliente_ibfk_1'),
    sa.ForeignKeyConstraint(['forma_pago_id'], ['forma_pago.id'], name='venta_cliente_ibfk_2'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name='venta_cliente_ibfk_3'),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], name='venta_cliente_ibfk_4'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('orden_pago')
    # ### end Alembic commands ###
