"""Cambio Venta

Revision ID: 1ac466467624
Revises: 81edeca86708
Create Date: 2024-08-11 23:39:06.544198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ac466467624'
down_revision = '81edeca86708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('estado')
        batch_op.drop_column('tipo_documento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_documento', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('estado', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
