"""Add clave unica a datos que no deben repetirse

Revision ID: 81edeca86708
Revises: 19fdebacceaa
Create Date: 2024-08-11 23:13:47.244090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81edeca86708'
down_revision = '19fdebacceaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('almacenamiento', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('caracteristica', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('compatibilidad', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('condicion', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('condicion_fiscal', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['cuit'])
        batch_op.create_unique_constraint(None, ['razon_social'])

    with op.batch_alter_table('forma_pago', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('garantia', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('pais', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('posicion', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('puesto', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('tipo', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('tipo_documento', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_documento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('tipo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('puesto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('posicion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('pais', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('garantia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('forma_pago', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('condicion_fiscal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('condicion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('compatibilidad', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('caracteristica', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('almacenamiento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
